Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "rhum")
Ingredient.create(name: "water")
Ingredient.create(name: "cachaca")
Ingredient.create(name: "tequila")
Ingredient.create(name: "whisky")
Ingredient.create(name: "gin")
Ingredient.create(name: "sirup")

Cocktail.create(name: "mojito")
Cocktail.create(name: "cosmopolitan")
Cocktail.create(name: "pina collada")
Cocktail.create(name: "sex on the beach")
